version: "3.9"

services:
  oracle:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle
    environment:
      ORACLE_PWD: MyStrongPass   # Initial SYSTEM/SYS password
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "1521:1521"              # Database listener
      - "5500:5500"              # EM Express
    volumes:
      - oracle_data:/opt/oracle/oradata  # Persistent storage
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'SELECT 1 FROM dual;' | sqlplus -s sys/MyStrongPass@//localhost:1521/FREEPDB1 as sysdba"]
      interval: 20s
      timeout: 10s
      retries: 10
    restart: unless-stopped

volumes:
  oracle_data:
    driver: local