version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  springboot-app:
    image: rakeshk459/restservice:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    command: >
      sh -c "
        echo 'Checking Postgres readiness...';
        until nc -z postgres 5432; do
          echo 'Waiting for Postgres to be ready...';
          sleep 2;
        done;
        echo 'Postgres is ready, starting Spring Boot...';
        java -jar app.jar
      "

volumes:
  pgdata: